### ISSUE TITLE
✨ Use fluent emoji

### ISSUE THREAD

**Issue by Lamparter** [RiversideValley/Plaza#1]
### 📄 Description

Currently, as forked from `mastodon`, Plaza uses `twemoji`.
It would be a million times better if it could use Fluent emoji (which is licensed under the `mit` license.)
This will be difficult though, as the current emoji tables (in `/public/emoji`) doesn't match the style of Microsoft's `fluentui-emoji` repo.

### 🗃️ Alternative solutions

I will need to decide which type of emoji; colour or 3d best.
Probably 3d as they are in `png` format.

### ✅ Tasks

```[tasklist]
- [ ] Add Microsoft emoji license
- [x] Decide whether to use `3d` or `colour`
- [ ] Add emoji files
```

**Comment by Lamparter** [comment]
Currently, `mastodon` emoji are in `svg` format. So I'll need to use `colour` emoji.
